### ISSUE TITLE
Orden Creada

### ISSUE THREAD

**Issue by miloha87** [microservices-udea/shop-udea-orders#7]
1. El carrito de compras para crear una orden debe enviar un evento con la la siguiente información básica:
- Datos del cliente
- Items: cada item debe tener los siguientes datos básicos.
  - id_producto
  - cantidad_producto
  - precio_unitario
- Subtotal
- Total
2. Al crear la orden de compras esta debe generar un id_orden y quedar en estado pendiente.
3.  Después de crear la orden se debe generar  un evento para reservar el inventario con la información de la orden y los items, para que se pueda validar si existe o no disponibilidad del producto.

**Comment by kerobero** [comment]
Se deben definir los contratos de los eventos que se espera recibir y que se quieren generar con cada uno de los equipos involucrados.

- Cart
- Catalog

**Comment by gustavo10xx** [comment]
Se hablo con  un representante del carrito de compras  y se propuso que nos publicaran sobre el siguiente formato en inicial : 
{
  "user-id": 1 ,
  "products": [{
    "product-id":1,
    "quantity":2,
    "price":3
  }]
}
Falta hablar con las personas del catalog para saber que información necesitan , deberíamos manejar un campo común en los eventos que publiquemos que sea el identificador del evento , propongo event-id="orderCreated".  Supongo que la idea seria agregar este campo al DTO y hacer la transformación para según los datos datos que se necesiten en cada publicación.

**Comment by kerobero** [comment]
Debería ser event-type en vez de event-id.

**Comment by kerobero** [comment]
Se debe solicitar información de la catergoria del producto al equipo de catalog para enviar esa información a accounting.
