### ISSUE TITLE
Orden Reservada

### ISSUE THREAD

**Issue by miloha87** [microservices-udea/shop-udea-orders#9]
Después de validar la disponibilidad de los productos en el servicio reservar Inventario se pueden tener los siguientes escenarios:
1.  Si existe disponibilidad de todos los productos agregados en el carrito de compra, se debe enviar colocar en la cola de pagos y realizar el envió de los productos.

2.  Si no existe disponibilidad de ningún producto, se debe anular la orden de compra y volver al carrito de compras, indicando que no existe disponibilidad de el o los productos.

3.  Si existe disponibilidad de un producto y de otro no, se debe anular la orden de compra y volver al carrito de compras donde se informara cuales son los productos que no tienen disponibilidad.

4. La información necesaria para el equipo de Payments es orderid,userid, y value.

**Comment by kerobero** [comment]
Se agregan los campos solicitados por el equipo de pagos en el punto 4.
